fix(use-controlled): value doest't change when controlledValue changed
rsuite/rsuite pull request #1742
Opened 2021-06-17 07:36 UTC by superman66

2021-06-17 07:40 UTC, SevenOutman commented
缺少了验证此变更的测试用例

2021-06-17 08:37 UTC, SevenOutman requested changes
缺少了验证此变更的测试用例

2021-06-18 05:43 UTC, simonguo commented on package-lock.json
> +      "resolved": "https://npm.hypers.cc/@testing-library%2freact-hooks/-/react-hooks-7.0.0.tgz",
registry 切换到 npm: registry.npmjs.org

2021-06-18 07:34 UTC, SevenOutman approved these changes
LGTM

2021-06-21 07:08 UTC, merged