fix(check-tree-picker): onChange does't return the correct value
rsuite/rsuite pull request #1743
Opened 2021-06-17 11:58 UTC by superman66

2021-06-17 15:18 UTC, SevenOutman requested changes

2021-06-17 15:18 UTC, SevenOutman commented on src/CheckTreePicker/CheckTreePicker.tsx
> -        del: handleClean
这里为什么要删去 `handleClean`?

2021-06-17 15:18 UTC, SevenOutman commented on src/CheckTreePicker/test/CheckTreePickerSpec.js
> +      ReactDOM.render(
这里最好和其他的用例一样使用 `getInstance()` 来创建 DOM

2021-06-17 15:18 UTC, SevenOutman commented on src/TreePicker/TreePicker.tsx
> -        del: handleClean
这个 PR 看起来不需要修改 TreePicker

2021-06-17 16:42 UTC, superman66 commented on src/CheckTreePicker/CheckTreePicker.tsx
> -        del: handleClean
https://github.com/rsuite/rsuite/blob/next/src/Picker/utils.ts#L414

`useToggleKeyDownEvent` hook 内部已经实现同样的功能了

2021-06-17 17:07 UTC, superman66 commented on src/TreePicker/TreePicker.tsx
> -        del: handleClean
https://github.com/rsuite/rsuite/pull/1745 
已迁移到该 PR

2021-06-18 09:51 UTC, SevenOutman approved these changes

2021-06-18 10:03 UTC, SevenOutman commented on src/CheckTreePicker/test/CheckTreePickerSpec.js
> +        done();
用 `done` 处理异步测试时也应当使用断言而不是 `if`，否则如果测试失败，错误信息只有"2000ms 内没有 done"，而无法得到更详细的错误信息。

```js
try {
  assert.equal(expectedValue, value);
  done();
} catch (err) {
  done(err); // 为 done 传入 err 参数来表示测试失败
}
```

另一种优化方式时使用 `sinon.spy()` 来创建 mock function：

```js
const mockOnChange = sinon.spy();

// do something

expect(mockOnChange).to.have.been.calledWith(expectedValue)
```

不过不影响合并此 PR。

2021-06-21 07:08 UTC, merged