docs(migration): add explanation for adding tinycolor2
rsuite/rsuite pull request #1794
Opened 2021-07-26 02:45 UTC by SevenOutman

2021-07-26 15:26 UTC, simonguo commented on docs/pages/guide/v5-features/en-US/index.md
> +    npm install -D tinycolor2
让每一个用户（特别是新手用户）都需要在去安装 tinycolor2 ， 这个体验不是很好。 
这里看看能不能继续沿用 v4 的方式: https://github.com/rsuite/rsuite/blob/master/src/styles/mixins/tiny-color.less

2021-07-28 05:55 UTC, simonguo requested changes

2021-07-28 05:55 UTC, simonguo commented on src/styles/plugins/palette.js
> -const tinycolor = require('tinycolor2');
移除 package.json 和 package-lock.json 中对 tinycolor2 的依赖。

2021-07-28 06:33 UTC, SevenOutman commented on src/styles/plugins/palette.js
> -const tinycolor = require('tinycolor2');
测试脚本中仍会用到 tinycolor2

2021-07-28 06:35 UTC, simonguo approved these changes

2021-07-28 06:35 UTC, merged