fix(nav): trigger `onSelect` on `<Nav>` when clicking `<Nav.Item>`
rsuite/rsuite pull request #1797
Opened 2021-07-26 06:06 UTC by SevenOutman

Fix #1795

2021-07-26 15:15 UTC, simonguo requested changes

2021-07-27 01:52 UTC, simonguo requested changes

2021-07-27 01:52 UTC, simonguo commented on src/Dropdown/Dropdown.tsx
> +  const { onSelect: onSelectFromNav } = useContext(NavContext);
Nav 设置 activeKey，未能使 Dropdown 及 Dropdown.Item 选中高亮
![image](https://user-images.githubusercontent.com/1203827/127082220-01c117b1-c8c8-4ca0-beb4-3a8d3dc2ddc9.png)

2021-07-27 16:39 UTC, SevenOutman commented on src/Dropdown/Dropdown.tsx
> +  const { onSelect: onSelectFromNav } = useContext(NavContext);
这种场景下如果 `<Nav>` 和 `<Dropdown>` 上都设置了 `activeKey`，是都选中吗？

2021-07-28 02:55 UTC, simonguo commented on src/Dropdown/Dropdown.tsx
> +  const { onSelect: onSelectFromNav } = useContext(NavContext);
我觉得可以都选中， 或者你看看哪种方式更合理。

2021-07-28 11:05 UTC, simonguo requested changes

2021-07-28 11:05 UTC, simonguo commented on src/Dropdown/Dropdown.tsx
> +  const { onSelect: onSelectFromNav } = useContext(NavContext);
在 Navbar 和  Sidenav 存在同样的问题

2021-07-28 11:46 UTC, SevenOutman commented on src/Dropdown/Dropdown.tsx
> +  const { onSelect: onSelectFromNav } = useContext(NavContext);
`<Sidenav>` 和 `<Navbar>` 都是要配合 `<Nav>` 来使用的，我在想 `<Sidenav>` 和 `<Navbar>` 本身也许并不需要 `activeKey` 属性？

2021-07-28 13:55 UTC, simonguo commented on src/Dropdown/Dropdown.tsx
> +  const { onSelect: onSelectFromNav } = useContext(NavContext);
是 Nav 的 activeKey 属性。
![image](https://user-images.githubusercontent.com/1203827/127334511-1f92b28e-1726-4a79-b9f8-6eea81dc03a4.png)

https://rsuite-next-git-fix-nav-onselect-rsuite.vercel.app/components/navbar/#appearance

2021-07-30 11:08 UTC, simonguo requested changes
Dropdown 在 Navbar 和 Sidenav 中都无法通过 Nav onSelect 选中选项。

https://rsuite-next-git-fix-nav-onselect-rsuite.vercel.app/components/sidenav/#appearance
https://rsuite-next-git-fix-nav-onselect-rsuite.vercel.app/components/navbar/#appearance

2021-07-31 12:04 UTC, SevenOutman commented
> Dropdown 在 Navbar 和 Sidenav 中都无法通过 Nav onSelect 选中选项。

已修复

2021-08-01 08:57 UTC, simonguo requested changes
在 Sidenav 中的三级选项还是不能选择
![image](https://user-images.githubusercontent.com/1203827/127765345-fb3c2de3-2c40-44b4-a760-d77c72f565fc.png)

2021-08-01 15:19 UTC, SevenOutman commented
> 在 Sidenav 中的三级选项还是不能选择

这个 example 里是在 `<Sidenav>` 上使用的 `activeKey` 和 `onSelect`。

![image](https://user-images.githubusercontent.com/8225666/127776190-bc17361c-5257-45a2-a7c9-b955ab3c6655.png)

如果改为设置在 `<Nav>` 上就是正常的。这里是否应该改为废弃 `<Sidenav>` 上的这两个属性，仅支持在 `<Nav>` 上设置？

2021-08-02 08:12 UTC, simonguo commented
> > 在 Sidenav 中的三级选项还是不能选择
> 
> 这个 example 里是在 `<Sidenav>` 上使用的 `activeKey` 和 `onSelect`。
> 
> ![image](https://user-images.githubusercontent.com/8225666/127776190-bc17361c-5257-45a2-a7c9-b955ab3c6655.png)
> 
> 如果改为设置在 `<Nav>` 上就是正常的。这里是否应该改为废弃 `<Sidenav>` 上的这两个属性，仅支持在 `<Nav>` 上设置？

废弃  `<Sidenav>` 的 `activeKey` 和 `onSelect` 吧，统一在 Nav 上设置，同时把 example 和 文档更新一下。

2021-08-03 10:18 UTC, SevenOutman commented
> 废弃 `<Sidenav>` 的 `activeKey` 和 `onSelect` 吧，统一在 Nav 上设置，同时把 example 和 文档更新一下。

已解决

2021-08-03 10:31 UTC, simonguo approved these changes

2021-08-03 10:33 UTC, merged