High contrast theme
rsuite/rsuite pull request #1828
Opened 2021-08-11 08:39 UTC by SevenOutman

https://www.figma.com/file/zxF7FCLlKqxoG8I7kbm41Y/NXT-UI-highcontrast?node-id=0%3A215

2021-09-08 11:18 UTC, simonguo requested changes
![image](https://user-images.githubusercontent.com/1203827/132500099-504b90da-fd3e-497d-9216-4684e4102ab2.png)
为 High contrast 切换添加一个 icon
![高对比度](https://user-images.githubusercontent.com/1203827/132500205-c73b245a-1493-4ad7-85fd-ca8ea6f1d430.png)

icon svg
```html
<svg t="1631100164073" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="2517" width="128" height="128"><path d="M512 134c51.06 0 100.55 9.99 147.12 29.68 45 19.04 85.44 46.3 120.17 81.03 34.74 34.74 62 75.17 81.04 120.17C880.01 411.45 890 460.94 890 512s-9.99 100.55-29.68 147.12c-19.04 45-46.3 85.44-81.04 120.17-34.74 34.74-75.17 62-120.17 81.04C612.55 880.01 563.06 890 512 890s-100.55-9.99-147.12-29.68c-45-19.04-85.44-46.3-120.17-81.04-34.74-34.74-62-75.17-81.03-120.17C143.99 612.55 134 563.06 134 512s9.99-100.55 29.68-147.11c19.04-45 46.3-85.44 81.03-120.17 34.74-34.74 75.17-62 120.17-81.03C411.45 143.99 460.94 134 512 134m0-64C267.89 70 70 267.89 70 512s197.89 442 442 442 442-197.89 442-442S756.11 70 512 70z" fill="#444444" p-id="2518"></path><path d="M512 828c174.52 0 316-141.48 316-316S686.52 196 512 196v632z" fill="#048BFF" p-id="2519"></path></svg>
```

2021-09-08 11:18 UTC, simonguo commented on src/Picker/styles/index.less
![image](https://user-images.githubusercontent.com/1203827/132498551-cfb6ebfd-d744-4a62-8ac1-e8a5c280534e.png)
picker-value-count 的文字颜色与背景不符合高对比度

2021-09-08 11:37 UTC, simonguo commented on docs/pages/components/navbar/zh-CN/index.md
> +
在文档帮助指南也需要添加对 High contrast 的说明。 
要么把以下这页改为 Dark & High contrast
https://rsuite-next-git-feat-high-contrast-theme-rsuite.vercel.app/guide/dark-mode/

2021-09-09 06:30 UTC, SevenOutman commented on src/Picker/styles/index.less
已修复

2021-09-09 06:46 UTC, SevenOutman commented on docs/pages/components/navbar/zh-CN/index.md
> +
添加了单独的 high-contrast mode 说明页

2021-09-09 07:45 UTC, simonguo approved these changes

2021-09-09 07:46 UTC, merged