chore: use proxyDirectories to build esm/cjs
rsuite/rsuite pull request #1830
Opened 2021-08-11 14:22 UTC by simonguo

Create a package.json for each directory and proxy to CJS and ESM files. 

## breaking change

### Manually import

```ts
// v4
import Button from 'rsuite/lib/Button';
import 'rsuite/lib/Button/styles/index.less'; 

// v5
import Button from 'rsuite/Button';
import 'rsuite/Button/styles/index.less'; 
```

### Import default style

```ts
// v4
import 'rsuite/lib/styles/index.less';

// v5
import 'rsuite/styles/index.less';
```

### Import locales

```ts
// v4
import ruRU from 'rsuite/lib/IntlProvider/locales/ru_RU';

// v5
import ruRU from 'rsuite/locales/ru_RU';
```

## Canary version

```
npm i rsuite@canary
```

2021-08-13 03:34 UTC, SevenOutman requested changes

2021-08-13 03:34 UTC, SevenOutman commented on test/validateBuilds.js
> +  'lib/esm/Button/index.js',
这里最好将所有进行 proxy 的组件都验证一下

2021-08-13 03:34 UTC, SevenOutman commented on test/validateBuilds.js
> +  'lib/Button/package.json',
这里最好将所有进行 proxy 的组件都验证一下

2021-08-16 02:39 UTC, SevenOutman reviewed
可以将 build 和 validateBuilds 添加到 CI 流程中

2021-08-16 04:07 UTC, simonguo commented
> 可以将 build 和 validateBuilds 添加到 CI 流程中

https://github.com/rsuite/rsuite/pull/1830/files#diff-b5b3f00efad43c9c37e817e3832422471a962213f30b7f2068dcfe5cdf5a09e5R137-R139
![image](https://user-images.githubusercontent.com/1203827/129510062-e9edbb00-1b85-47d2-b46e-4095ef67aead.png)

 在每次发布新的版本的时候会在 CI 中执行 build 和 validateBuilds

2021-08-16 05:14 UTC, SevenOutman approved these changes

2021-08-16 08:29 UTC, merged