feat: support time selection of `DateRangePicker`
rsuite/rsuite pull request #1882
Opened 2021-09-02 09:41 UTC by LeiHanCN

2021-09-16 03:57 UTC, simonguo requested changes

2021-09-16 03:57 UTC, simonguo commented on src/DateRangePicker/DateRangePicker.tsx
> +      if (!isSameValueType(nextValue, value)) {
`isSameValueType` 不太好理解，建议改为 `isSameDateRange`

2021-09-16 03:57 UTC, simonguo commented on src/DateRangePicker/DateRangePicker.tsx
> +      });
这里是不是可以直接 `next[index] = date;`  为什么需要单独去设置时间？

2021-09-16 03:57 UTC, simonguo commented on src/DateRangePicker/test/DateRangePickerSpec.js
> +        }}
这个测试用例最好能够去掉 `renderValue` , 检查一下组件默认渲染结果是否满足预期。

2021-09-16 03:57 UTC, simonguo commented on src/DateRangePicker/test/DateRangePickerSpec.js
> +    const onOkSpy = sinon.spy();
`onOkSpy` 定义了，但未使用

2021-09-16 03:57 UTC, simonguo commented on src/DateRangePicker/test/DateRangePickerSpec.js
> +    ReactTestUtils.Simulate.click(picker.querySelector(generateTimeItem(0, 'seconds', 7)));
这里点击时间后，可以加一个断言，检查是否正常渲染。

2021-09-16 03:57 UTC, simonguo commented on src/DateRangePicker/test/DateRangePickerSpec.js
> +    ReactTestUtils.Simulate.click(picker.querySelector(generateTimeItem(1, 'seconds', 10)));
这里也可以加一个断言，检查是否正常渲染。

2021-09-16 03:57 UTC, simonguo commented on src/DateRangePicker/test/DateRangePickerSpec.js
> +    const onOkSpy = sinon.spy();
或者这里监听 onChange 回调，点击 ok 后，断言更新后的时间是否满足预期

2021-09-16 03:58 UTC, SevenOutman requested changes
请先 rebase 到最新的 `next` 分支

2021-09-17 10:29 UTC, simonguo commented on src/DateRangePicker/DateRangePicker.tsx
> +
```js
const nextValue = Array.from(selectValue);
nextValue[index] = date;
      
setSelectValue(nextValue);
```
我的意思是这里可以直接赋值 date，为什么需要单独把 hour，minutes， seconds 重新设置。

2021-09-22 09:27 UTC, simonguo requested changes

2021-09-22 09:27 UTC, simonguo commented on docs/pages/components/date-range-picker/fragments/format-date-time.md
> +    <DateRangePicker format="HH:mm:ss" />
建议设置一个 ranges
```tsx 
<DateRangePicker format="HH:mm:ss" ranges={[]} />
```
![image](https://user-images.githubusercontent.com/1203827/134317937-7bf12e3a-6daa-4f99-adfd-13faaf3bd88c.png)

2021-09-22 09:27 UTC, simonguo commented on src/DateRangePicker/test/DateRangePickerSpec.js
> +      instance.target.querySelector('.rs-picker-toggle-value').innerText,
建议把 innerText 改为 textContent，因为 innerText Safari 浏览器取值时候会存在多余的换行符
https://github.com/rsuite/rsuite/pull/1917/files#diff-0b2524eb182158bf69ca0ba666167dc2629cee0ea82c06063f81af769f4217abR45

2021-09-22 09:27 UTC, simonguo commented on src/DateRangePicker/test/DateRangePickerSpec.js
> +      instance.target.querySelector('.rs-picker-toggle-value').innerText,
建议把 innerText 改为 textContent

2021-09-22 10:05 UTC, simonguo approved these changes

2021-09-22 17:27 UTC, SevenOutman requested changes
有很多无关的代码格式化变更，应当排除

2021-09-23 02:29 UTC, LeiHanCN commented
> 有很多无关的代码格式化变更，应当排除

这只是跑了四个 format 脚本出来的结果，不跑 format 跑不了 CI 测试 @SevenOutman

2021-09-23 06:30 UTC, SevenOutman commented
> 这只是跑了四个 format 脚本出来的结果，不跑 format 跑不了 CI 测试 @SevenOutman

CI 检查不通过的应该是你在 src/ 目录里的改动。可 docs/ 目录里有太多与这个 PR 主题完全无关的变更了，例如这种 https://github.com/rsuite/rsuite/pull/1882/files#diff-81f737c6bf1ba5ae7f5ba4ea11b82387cb373b7871022056f54de4eb69b759af。

2021-09-23 09:50 UTC, SevenOutman requested changes
docs/client/polyfills.ts

2021-09-23 09:50 UTC, SevenOutman commented on src/DateRangePicker/test/DateRangePickerSpec.js
> +  });
用例中 `now` 的取值以及比较的 `${format(yesterday, template)} ~ ${format(now, template)}` 应为固定值，例如：
```js
assert.equal(
  instance.target.querySelector('.rs-picker-toggle-value').textContent,
  `09/22/2021 17:31:00 ~ 09/23/2021 17:31:00`
);
```

2021-09-23 09:50 UTC, SevenOutman commented on src/DateRangePicker/test/DateRangePickerSpec.js
> +    );
同上，用例中用于比较的输入输出应为固定值

2021-09-23 09:50 UTC, SevenOutman commented on src/DateRangePicker/test/DateRangePickerSpec.js
> +    );
同上，用例中用于比较的输入输出应为固定值

2021-09-23 09:50 UTC, SevenOutman commented on src/DateRangePicker/utils.ts
> +  source?.[1]?.toString() === dest?.[1]?.toString();
我看到你用这个方法[代替了 `isSameDay`](https://github.com/rsuite/rsuite/pull/1882/files#diff-7f89a1ffee8cf9975c367c9826b37a1f35d7ca45e6b0b334386320badc61dc84L319-R332)，但是从这两行来看它只是在比较 source 和 dest 是否完全相同，这是否会使得在 source 与 dest 日期相同而时间不同时，与原来的表现有所不同？

2021-09-24 03:08 UTC, SevenOutman requested changes

2021-09-24 03:08 UTC, SevenOutman commented on src/DateRangePicker/test/DateRangePickerSpec.js
> +    const value = [new Date('11/11 2019 01:00:00'), new Date('11/12 2019 01:00:00')];
不要在 `new Date(dateString)` 构造器中使用非标准的日期时间字符串，改为 `new Date(year, monthIndex, date, hours)` 以避免其在不同浏览器中表现不一致。

2021-09-24 03:08 UTC, SevenOutman commented on src/DateRangePicker/test/DateRangePickerSpec.js
> +    const value = [new Date('11/11 2019 00:00:00'), new Date('11/12 2019 00:00:00')];
同上，调整 `new Date()` 构造器的参数

2021-09-24 03:08 UTC, SevenOutman commented on src/DateRangePicker/test/DateRangePickerSpec.js
> +    const start = new Date('11/11 2019 00:00:00');
同上，调整 `new Date()` 构造器的参数

2021-09-24 03:08 UTC, SevenOutman commented on docs/pages/components/date-range-picker/en-US/index.md
> +| format               | string `('yyyy-MM-dd')`                                 | Format date                                                                          |
这里可以说明一下允许的格式有哪些，例如“允许 `date-fns` 支持的所有 format 格式”。

2021-09-24 09:35 UTC, SevenOutman approved these changes

2021-09-24 09:49 UTC, merged