test: fix cross browser test
rsuite/rsuite pull request #1917
Opened 2021-09-19 10:24 UTC by SevenOutman

2021-09-22 09:50 UTC, simonguo requested changes

2021-09-22 09:50 UTC, simonguo commented on package.json
> +    "ie 11"
last 2 versions  包含了 ie10 和 ie11。 
建议改为 `last 1 versions or > 1%`
https://browserslist.dev/?q=bGFzdCAxIHZlcnNpb25zIG9yID4gMSU%3D

2021-09-22 11:19 UTC, SevenOutman commented on package.json
> +    "ie 11"
好像可以用 `not ie <11` 来移除不需要的版本

https://browserslist.dev/?q=bGFzdCAyIHZlcnNpb25zIG9yID4gMSUgYW5kIG5vdCBpZSA8MTE%3D

2021-09-22 11:24 UTC, simonguo commented on package.json
> +    "ie 11"
👌

2021-09-23 03:33 UTC, simonguo approved these changes

2021-09-23 03:37 UTC, merged