fix(sidenav): fix nav item not activated in collapsed sidenav
rsuite/rsuite pull request #1918
Opened 2021-09-22 09:11 UTC by SevenOutman

2021-09-22 10:01 UTC, simonguo requested changes

2021-09-22 10:01 UTC, simonguo commented on src/Sidenav/SidenavItem.tsx
> +          });
dropdown.item 缺少 active 的样式
![image](https://user-images.githubusercontent.com/1203827/134323774-2c8cdd71-4570-4253-bec5-b58b7308b649.png)

2021-09-22 17:22 UTC, SevenOutman commented on src/Sidenav/SidenavItem.tsx
> +          });
已修复

2021-09-23 03:25 UTC, simonguo approved these changes

2021-09-23 03:33 UTC, merged