refactor(Toggle): add underlying input element
rsuite/rsuite pull request #2079
Opened 2021-10-30 07:02 UTC by SevenOutman

2021-11-01 02:50 UTC, simonguo requested changes

2021-11-01 02:50 UTC, simonguo commented on src/Toggle/Toggle.tsx
> +        hidden
![image](https://user-images.githubusercontent.com/1203827/139614739-0c0e0499-03d2-4b8a-9655-93f193aa3a2d.png)
可以把根元素改为 label ,  input 可以为一个 100% 撑满的透明度为 0 元素。  这样的情况下就可以删除根元素上的 onClick 和 onKeyDown 事件， 只需要一个 input change 事件就行了。  同时 document.activeElement  获取到的元素是 input

2021-11-01 08:07 UTC, SevenOutman commented on src/Toggle/Toggle.tsx
> +        hidden
这样一来 `<Toggle>` 是否不再支持 `as` 属性？

2021-11-01 09:06 UTC, simonguo commented on src/Toggle/Toggle.tsx
> +        hidden
如果没有其他办法的，可以不要。

2021-11-01 11:57 UTC, simonguo requested changes

2021-11-01 11:57 UTC, simonguo commented on src/Toggle/styles/index.less
为 toggle 添加一个 focus 状态
```css
.rs-toggle-input:focus + .rs-toggle-presentation {
    box-shadow: var(--rs-state-focus-shadow);
}
```

2021-11-02 04:08 UTC, SevenOutman commented on src/Toggle/styles/index.less
添加了 `:focus-visible` 选择器以仅在通过键盘聚焦时显示效果

2021-11-02 10:01 UTC, simonguo approved these changes

2021-11-03 03:10 UTC, merged