Update guide for using with Next.js
rsuite/rsuite pull request #2145
Opened 2021-11-21 09:32 UTC by SevenOutman

This PR is basically a replacement of the inactive #2030.

2021-11-23 01:40 UTC, simonguo requested changes

2021-11-23 01:40 UTC, simonguo commented on docs/pages/guide/use-next-app/en-US/index.md
>  There are some navigation components in the rsuite component, such as `Dropdown`, `Nav`, `Breadcrumb`, which are used in conjunction with the `Link` component of `Next.js` to use the `renderItem` met
`renderItem`  的使用方式已经弃用，改为 `as`。

2021-11-23 01:40 UTC, simonguo commented on docs/pages/guide/use-next-app/en-US/index.md
> +Import RSuite style in your `_app.js` (or `_app.tsx`).
这里的 `RSuite` ， 我们统一两种书写方式吧： `rsuite` 与 `React Suite`.

2021-11-24 03:19 UTC, SevenOutman commented on docs/pages/guide/use-next-app/en-US/index.md
> +Import RSuite style in your `_app.js` (or `_app.tsx`).
好

2021-11-24 05:10 UTC, simonguo approved these changes

2021-11-24 05:17 UTC, merged