fix(Radio): fix unclickable without children
rsuite/rsuite pull request #2190
Opened 2021-12-09 00:09 UTC by MarvelSQ

close #2188

2021-12-14 08:52 UTC, simonguo requested changes

2021-12-14 08:52 UTC, simonguo commented on src/Radio/Radio.tsx
> +        <label title={title}>
建议使用 CSS 解决当前问题。 当用户在使用 Radio 的时候，允许他在没有 children 的情况下，可以在外层自定义套一个 label
![wecom-temp-21d168c0ea2b55a157275c973d877d69](https://user-images.githubusercontent.com/1203827/145964741-58cbf1de-5135-473f-b63f-595c7751e7c3.png)

2021-12-16 13:29 UTC, MarvelSQ commented on src/Radio/Radio.tsx
> +        <label title={title}>
设置CSS，提高 input 层级，允许直接操作

2021-12-17 02:09 UTC, simonguo approved these changes

2021-12-17 09:30 UTC, merged