fix(SelectPicker): fix onChange argument type
rsuite/rsuite pull request #2193
Opened 2021-12-09 10:21 UTC by SevenOutman

The value type used to be fixed as `number | string` on `<SelectPicker>`.

![wecom-temp-4c36685ca532bc943b5dbeedb56602c4](https://user-images.githubusercontent.com/8225666/145378304-86ec92f2-0403-4036-b3e2-5661f286b95d.png)

Now `value` and `onChange(value)` types are inferred from `data` prop.

2021-12-10 01:48 UTC, simonguo requested changes

2021-12-10 01:48 UTC, simonguo commented on src/SelectPicker/test/SelectPicker.test.tsx
> +    expectType<string>(newValue);
![image](https://user-images.githubusercontent.com/1203827/145503212-717c8211-6d30-4021-80e6-2c80715f802b.png)
```
Argument of type 'ValueType' is not assignable to parameter of type 'string'.
  Type 'number' is not assignable to type 'string'
```

2021-12-10 01:48 UTC, simonguo commented on src/SelectPicker/test/SelectPicker.test.tsx
> +/>;
需要添加一个测试用例:
```tsx
const handleChange = (value: string) => {
  console.log(value);
};
<SelectPicker data={stringValuedData} onChange={handleChange} />;
```

![image](https://user-images.githubusercontent.com/1203827/145503516-a163bfd0-c0fc-4e29-a18a-c6933f00a533.png)

2021-12-10 04:48 UTC, SevenOutman commented on src/SelectPicker/test/SelectPicker.test.tsx
> +/>;
这个和上面应该是同一个问题

2021-12-10 08:55 UTC, SevenOutman commented on src/SelectPicker/test/SelectPicker.test.tsx
> +    expectType<string>(newValue);
应该不会有这个问题才对，否则 CI 过程会无法通过 `tsc` 检查的。会不会是本地的依赖不是最新的？

2021-12-14 08:46 UTC, simonguo approved these changes

2021-12-14 08:49 UTC, merged