fix(Radio): fix Radio enabled under disabled RadioGroup
rsuite/rsuite pull request #2226
Opened 2021-12-16 02:57 UTC by MarvelSQ

fix #2224

2021-12-16 05:35 UTC, simonguo requested changes

2021-12-16 05:35 UTC, simonguo commented on src/RadioGroup/test/RadioGroupSpec.js
> +    assert.ok(instance.querySelectorAll('.rs-radio-disabled').length === 4);
```suggestion
    assert.equal(instance.querySelectorAll('.rs-radio-disabled').length, 4);
```

2021-12-16 05:35 UTC, simonguo commented on src/Radio/Radio.tsx
> +    disabled: propsDisabled = disabledContext,
```suggestion
    disabled: disabledProp = disabledContext,
```

2021-12-16 05:35 UTC, simonguo commented on src/Radio/Radio.tsx
> +  const disabled = disabledContext || propsDisabled;
```suggestion
  const disabled = typeof disabledContext === 'undefined' ? disabledProp : disabledContext;
```

2021-12-16 06:14 UTC, MarvelSQ commented on src/Radio/Radio.tsx
> +  const disabled = disabledContext || propsDisabled;
> 

```jsx
```

2021-12-16 06:19 UTC, MarvelSQ commented on src/Radio/Radio.tsx
> +    disabled: propsDisabled = disabledContext,
重命名 并 取消默认值

2021-12-16 06:41 UTC, simonguo commented on src/Radio/Radio.tsx
> +  const disabled = disabledContext || propsDisabled;
我觉得这还不能这样修复，如果 disabled 按照这个逻辑的话，readOnly  和   plaintext  是不是都有按照这个逻辑。 Checkbox 里面还有类似的问题。

另外，现在的逻辑也可以说的通，就像我们设置样式一样， 行内样式 style 的权重肯定比 `className` 样式的权重高。
所以当 Radio 设置 disabled 以后，是可以覆盖 context 的值。

2021-12-16 07:18 UTC, MarvelSQ commented on src/Radio/Radio.tsx
> +  const disabled = disabledContext || propsDisabled;
我也是认为，现有逻辑有合理性，但从UI角度出发，整个组件都是禁用，结果出现了一个启用项，违反直觉。

之后编写逻辑都要写成双重检查
```jsx
const isDisabled = ....
const isChildDisabled = ...

<RadioGroup disabled={isDisabled}>
  <Radio 
    // 双重检查
    disabled={isDisabled || isChildDisabled}
  >
    ...
  </Radio>
</RadioGroup>
```

2021-12-16 09:43 UTC, simonguo commented on src/Radio/Radio.tsx
> +  const disabled = disabledContext || propsDisabled;
什么样的业务场景上需要同时管理 RadioGroup  Radio 的状态？

2021-12-16 13:36 UTC, MarvelSQ commented on src/Radio/Radio.tsx
> +  const disabled = disabledContext || propsDisabled;
一个单项选择器，仅在创建时支持修改，编辑状态下为禁用
其中的子项的是否可选取决于对应分类下是否有数据，数据为空的情况，禁止选择该子项

2021-12-27 10:13 UTC, MarvelSQ commented on src/Radio/Radio.tsx
> +  const disabled = disabledContext || propsDisabled;
@simonguo 这个禁用逻辑要变更吗？

2021-12-27 10:45 UTC, simonguo commented on src/Radio/Radio.tsx
> +  const disabled = disabledContext || propsDisabled;
我觉得禁用逻辑不要变更，和 readOnly 、 plaintext 保持一致。

2022-04-03 13:29 UTC, closed without merging