test: catch errors and warnings that are not caught in the test
rsuite/rsuite pull request #2247
Opened 2021-12-21 07:06 UTC by simonguo

2021-12-24 08:27 UTC, SevenOutman requested changes

2021-12-24 08:27 UTC, SevenOutman commented on src/Picker/PickerToggle.tsx
>            inputRef.current?.blur();
这里前面判断过 `inputRef.current` 存在，后面调用 `blur()` 就不需要加 `?` 了

2021-12-24 08:27 UTC, SevenOutman commented on src/Uploader/Uploader.tsx
> +    };
这里两次设为 `null` 是否重复了？

2021-12-24 08:27 UTC, SevenOutman commented on src/utils/useClickOutside.ts
> +    };
这里是否不必要将 ref 设为 `null`？后面已在组件卸载时移除了事件监听器

2021-12-24 10:50 UTC, simonguo commented on src/Cascader/test/CascaderSpec.js
> +      );
`onOpen` 和 `onClose` 是在动画执行结束后执行的，有延迟。

2021-12-24 11:07 UTC, SevenOutman commented on src/Cascader/test/CascaderSpec.js
> +      );
那这个 case 验证的点就变了。
可以用 [`@testing-library/react` 的 `waitFor` 函数](https://testing-library.com/docs/dom-testing-library/api-async)来测异步结果。

2021-12-26 01:45 UTC, simonguo commented on src/Cascader/test/CascaderSpec.js
> +      );
我试试

2022-01-04 09:20 UTC, SevenOutman approved these changes

2022-01-05 06:21 UTC, merged