fix(Tree): fix dragNode has cyclic object #2268
rsuite/rsuite pull request #2281
Opened 2022-01-06 07:20 UTC by superman66

2022-01-06 08:36 UTC, simonguo requested changes

2022-01-06 08:36 UTC, simonguo commented on src/utils/treeUtils.ts
> +    const cloneDragNode = { ...dragNode };
https://github.com/rsuite/rsuite/issues/2268
为 onDrop 添加一个单元测试，断言测试用例不抛出异常。

2022-01-12 02:29 UTC, simonguo reviewed
CheckTree 是否存在相同的问题？

2022-01-12 04:11 UTC, superman66 commented
> 

CheckTree 没有拖拽功能，并不会受影响

2022-01-13 08:12 UTC, simonguo approved these changes

2022-01-13 08:24 UTC, merged