fix(IconButton): infer addtional props from as prop
rsuite/rsuite pull request #2343
Opened 2022-02-09 10:30 UTC by SevenOutman

2022-02-09 10:41 UTC, simonguo requested changes

2022-02-09 10:41 UTC, simonguo commented on src/IconButton/IconButton.tsx
> +    ref?: React.Ref<HTMLElement>;
![image](https://user-images.githubusercontent.com/1203827/153181760-7e54900e-8716-42f7-8eb6-029532ca2db6.png)

2022-02-10 06:40 UTC, SevenOutman commented on src/IconButton/IconButton.tsx
> +    ref?: React.Ref<HTMLElement>;
已修改 LanguageButton 中的类型声明

2022-02-10 09:30 UTC, simonguo approved these changes

2022-02-10 11:11 UTC, merged