feat(Cascader): add `renderSearchItem` for customizing search result
rsuite/rsuite pull request #2427
Opened 2022-03-31 07:12 UTC by MarvelSQ

# CHANGES

- add `renderSearchItem` for customizing search result

## renderSearchItem
```ts
{
  renderSearchItem?: (itemLabel: React.ReactNode, item: ItemDataType) => React.ReactNode;
}
```

2022-04-01 03:57 UTC, SevenOutman commented on src/Cascader/Cascader.tsx
> +
I'd suggest passing the complete parent-child path of the search result as arguments for flexibility.
```suggestion
  /** Custom render search items */
  renderSearchItem?: (itemLabel: React.ReactNode, items: ItemDataType[]) => React.ReactNode;

```

2022-04-02 02:24 UTC, simonguo approved these changes

2022-04-02 02:41 UTC, SevenOutman requested changes
Please add a test case for the `items` argument

2022-04-03 11:43 UTC, SevenOutman approved these changes

2022-04-07 11:03 UTC, merged