refactor(Dropdown,Nav): decouple Dropdown from usage within Nav
rsuite/rsuite pull request #2458
Opened 2022-04-18 05:56 UTC by SevenOutman

2022-05-06 13:03 UTC, simonguo requested changes

2022-05-10 14:33 UTC, SevenOutman commented on docs/pages/components/sidenav/fragments/collapsed.md
> +              <Nav.Menu eventKey="4-5" title="Custom Action">
这个示例里没有做受控，是选不中的。下面的示例里可以看出是正常的 https://rsuite-nextjs-git-refactor-decouple-dropdown-nav-rsuite.vercel.app/components/sidenav/#appearance

2022-05-11 04:00 UTC, simonguo commented on docs/pages/components/sidenav/fragments/collapsed.md
> +              <Nav.Menu eventKey="4-5" title="Custom Action">
折叠后是可以选中的
<img width="441" alt="image" src="https://user-images.githubusercontent.com/1203827/167766495-bc82c3a2-f78f-41d4-9c15-d7a83b77bdb8.png">

2022-05-12 02:08 UTC, SevenOutman commented on docs/pages/components/sidenav/fragments/collapsed.md
> +              <Nav.Menu eventKey="4-5" title="Custom Action">
这里是因为示例代码里使用了已废弃的 prop 导致的，修改了示例后好了。

2022-05-12 02:14 UTC, SevenOutman commented on src/Dropdown/Dropdown.tsx
> +    return <Nav.Menu ref={ref} {...props} />;
现已兼容，不再抛出错误，但表现略有不同。

2022-05-13 03:19 UTC, simonguo requested changes

2022-05-13 03:19 UTC, simonguo commented on src/Sidenav/SidenavDropdownMenu.tsx
> +      '<Sidenav.Dropdown.Menu> must be rendered within a <Nav> within a <Sidenav> component.'
`<Sidenav.Dropdown.Menu>` 这里的命名与下面 displayName 命名不一致 https://github.com/rsuite/rsuite/pull/2458/files#diff-0f6e66effbd97b7bd552748e434a407024e9de3022d762feb0bbe84455353dbeR169

2022-05-13 16:59 UTC, SevenOutman commented on src/Sidenav/SidenavDropdownMenu.tsx
> +      '<Sidenav.Dropdown.Menu> must be rendered within a <Nav> within a <Sidenav> component.'
已修改

2022-05-17 08:36 UTC, SevenOutman commented
> * doc: Nav.Menu 需要在文档 Props [添加对应的说明](https://rsuite-nextjs-git-refactor-decouple-dropdown-nav-rsuite.vercel.app/components/nav/#code-lt-nav-dropdown-gt-code)
> * doc: 在组件Overview页面，[Nav.Dropdown 重名为 Nav.Menu](https://github.com/rsuite/rsuite/blob/main/docs/utils/component.config.json#L154)

已补充

2022-05-19 08:36 UTC, simonguo approved these changes

2022-05-19 08:44 UTC, merged