feat: formControl add unMountRemove prop
rsuite/rsuite pull request #2468
Opened 2022-04-24 10:23 UTC by myNameIsDu

feat: formControl add unMountRemove prop

Support for deleting value and error when unMount

There is a problem:
The onchange call passes no event and originally defines the second parameter as event, I think it's a disruptive change
Maybe there is another way to handle it? Or maybe it doesn't matter?

2022-04-26 03:07 UTC, simonguo requested changes

2022-04-26 03:07 UTC, simonguo commented on src/FormControl/FormControl.tsx
> +  /** when unMount remove value and error  */
同步需要更新文档 
https://github.com/rsuite/rsuite/blob/main/docs/pages/components/form/en-US/index.md#formcontrol

2022-04-26 06:23 UTC, myNameIsDu commented on src/FormControl/FormControl.tsx
> +  /** when unMount remove value and error  */
done

2022-04-26 06:23 UTC, myNameIsDu commented on src/FormControl/FormControl.tsx
> +  unMountRemove?: boolean;
done

2022-04-26 06:23 UTC, myNameIsDu commented on src/FormControl/FormControl.tsx
> +  useUnmountRemove(unMountRemove, name, removeFieldValue, removeFieldError);
done

2022-04-27 03:37 UTC, simonguo requested changes

2022-04-27 03:37 UTC, simonguo commented on src/FormControl/FormControl.tsx
> +  useWillUnmount(handleUnmountReset);
`formValue` 会一直导致是  removeFieldValue 是可变的，这里用 useCallback 意义不大。
```suggestion
  useWillUnmount(()=>{
    if (shouldResetWithUnmount) {
      removeFieldValue?.(name);
      removeFieldError?.(name);
    }
  });
```

2022-04-27 04:10 UTC, myNameIsDu commented on src/FormControl/FormControl.tsx
> +  useWillUnmount(handleUnmountReset);
done

2022-04-27 07:11 UTC, simonguo approved these changes

2022-04-27 13:52 UTC, merged