feat(FormControl): support rule on <FormControl>
rsuite/rsuite pull request #2482
Opened 2022-05-05 21:45 UTC by myNameIsDu

formControl support rule prop

solve  problems
1. all mods exist at the top level, resulting in huge files.
2. not flexible enough, in the case of dynamic forms, if a new field is added or a field is deleted, it is necessary to manipulate the model at the top level

2022-05-06 07:49 UTC, simonguo requested changes
需要完善文档中的示例与 API 说明

2022-05-06 07:49 UTC, simonguo commented on src/FormControl/test/FormControlSpec.js
> +        }}
测试用例存在漏洞，如果程序不执行 `onError` 导致用例失去意义

2022-05-06 07:49 UTC, simonguo commented on src/Form/useSchemaModel.ts
> +    return () => {
- 这里是一个匿名方法，如果通过命名清楚知道方法内部是在做什么，建议添加注释。
- 如果是为了组件卸载时候把字段的规则移除，是不是可以把 push  和  remove 分开。

2022-05-06 07:49 UTC, simonguo commented on src/FormControl/test/FormControlSpec.js
>  });
缺少测试用例： 如果 Form 中的 model 与 FormControl 上 rule 同时存在了，验证的规则是什么样的？ 是都需要验证，还是优先那个？

2022-05-06 11:35 UTC, myNameIsDu commented on src/Form/useSchemaModel.ts
> +          .map(({ name, fieldRule }) => ({ [name]: fieldRule.current! }))
done

2022-05-06 20:19 UTC, myNameIsDu commented on src/Form/Form.tsx
> +  const [generatorModel, registerModel] = useSchemaModel(parentModel);
done

2022-05-06 20:19 UTC, myNameIsDu commented on src/Form/Form.tsx
> +    model: parentModel = SchemaModel({}),
done

2022-05-06 20:24 UTC, myNameIsDu commented on src/Form/Form.tsx
> +      const model = generatorModel();
这个如果写在外面的话会拿不到最新的各个字段的 rule ，因为子组件是用ref把rule同步给了父组件

2022-05-06 20:28 UTC, myNameIsDu commented on src/FormControl/test/FormControlSpec.js
> +        }}
那我应该用哪种方法去验证呢，我是觉得看做一个黑盒，model 对应的就是 error ，校验 error 会好一些

2022-05-07 02:30 UTC, simonguo commented on src/FormControl/test/FormControlSpec.js
> +        }}
参考：https://github.com/rsuite/rsuite/blob/main/src/CheckPicker/test/CheckPickerSpec.js#L176-L177
添加两个断言，确保 onError 被调用，同时校验回调参数

2022-05-07 04:50 UTC, simonguo commented on src/Form/Form.tsx
> +      const model = generatorModel();
还有一种思路， 修改 `useSchemaModel`


```tsx
const useSchemaModel = formModel => {
  const combinedModel = useRef(formModel);

  const pushFieldRule = (name, fieldRule) => {
    combinedModel.current = SchemaModel.combine(
      combinedModel.current,
      ...
    );
  };

  const removeFieldRule=(name)=>{
    ....
  }

  return {
    model: combinedModel.current,
    pushFieldRule,
    removeFieldRule
  };
};
```

这样 model 就始终拿到的是最新的，并不会产生频繁的 combine
```tsx
const { model, pushFieldRule } = useSchemaModel(formModel);
```

2022-05-07 07:32 UTC, myNameIsDu commented on src/FormControl/test/FormControlSpec.js
> +        }}
done

2022-05-07 07:38 UTC, myNameIsDu commented on src/Form/Form.tsx
> +      const model = generatorModel();
这样应该不行，因为调用push的时候，`SchemaModel.combine` 返回了一个新的对象，但是form没有更新，所以返回出去的是旧的，但是如果把 `combinedModel` 整个返回出去，在使用的时候使用 model.current 应该是可行的

2022-05-07 08:00 UTC, myNameIsDu commented on src/Form/useSchemaModel.ts
> +    return () => {
done

2022-05-07 15:41 UTC, myNameIsDu commented on src/FormControl/test/FormControlSpec.js
>  });
done

2022-05-07 20:38 UTC, myNameIsDu commented on src/Form/Form.tsx
> +      const model = generatorModel();
这个还有一个问题就是
```
 const combinedModel = useRef(formModel);
``` 
formModel 同步的问题，这样的写法`formModel` 只在挂载时存了一下，之后变化后就不生效了，但是如果
```
 const combinedModel = useRef(formModel);
combinedModel.current = forModel 
```
这样的写法 formModel 又会与 field 的rule 产生竞态

2022-05-07 20:41 UTC, myNameIsDu commented
> 需要完善文档中的示例与 API 说明

done

2022-05-09 13:11 UTC, simonguo commented on docs/pages/components/form/en-US/index.md
> +| rule                   | checkType                                             | Current field verification rule. If it conflicts with the `<Form>`'s `model`, it get higher priority, [example](/com
这里推荐是 vscode 的插件，给 markdown 中的 table 进行排序。
https://marketplace.visualstudio.com/items?itemName=simonguo.vscode-markdown-table-sort

2022-05-09 15:54 UTC, myNameIsDu commented on docs/pages/components/form/en-US/index.md
> +| rule                   | checkType                                             | Current field verification rule. If it conflicts with the `<Form>`'s `model`, it get higher priority, [example](/com
done

2022-05-11 03:56 UTC, simonguo approved these changes

2022-05-11 13:22 UTC, merged