fix(NavMenu): fix `noCaret` has No Effect on a Sub-menu
rsuite/rsuite pull request #2960
Opened 2022-12-05 05:16 UTC by Yuiai01

当 `<Nav.Menu>` 组件被嵌套时，会返回 `NavDropdownMenu` 组件，但是 `NavDropdownMenu` 并没有支持通过 `noCaret `属性配置小箭头图标的隐藏，因此此处通过为 `NavDropdownMenu` 组件接收 `noCaret` 属性并根据该属性控制是否显示小箭头图标。
问题来源:  [#2959](https://github.com/rsuite/rsuite/issues/2959)

修改前后示例：

**修改前**
![image](https://user-images.githubusercontent.com/112228030/205554807-fef5c49a-898a-48f6-afe2-426c2dc4fedf.png)
**修改后**
![image](https://user-images.githubusercontent.com/112228030/205554888-d0195885-c61b-4938-b521-57664a5d8878.png)

2022-12-05 06:26 UTC, simonguo requested changes
你需要为修复的问题，添加测试用例。 运行单个组件测试用例的命令是:

```bash
M=Nav npm run tdd
```

2022-12-05 09:28 UTC, Yuiai01 commented
> 你需要为修复的问题，添加测试用例。 运行单个组件测试用例的命令是:
> 
> ```shell
> M=Nav npm run tdd
> ```

嗯嗯

2022-12-07 01:53 UTC, Yuiai01 commented
> 你需要为修复的问题，添加测试用例。 运行单个组件测试用例的命令是:
> 
> ```shell
> M=Nav npm run tdd
> ```

大佬我按照要求添加了测试用例

2022-12-07 11:02 UTC, simonguo requested changes

2022-12-07 11:02 UTC, simonguo commented on src/Nav/test/NavMenuSpec.tsx
> +      assert.isNull(getByText('Submenu').querySelector('.rs-dropdown-menu-toggle-icon'));
```suggestion
      expect(getByText('Submenu').querySelector('.rs-dropdown-menu-toggle-icon')).to.not.exist;;
```

2022-12-07 11:08 UTC, Yuiai01 commented on src/Nav/test/NavMenuSpec.tsx
> +      assert.isNull(getByText('Submenu').querySelector('.rs-dropdown-menu-toggle-icon'));
> 

好的大佬，测试用例代码不是很会，有没有相关的推荐文档或者书籍学习呢？

2022-12-07 11:46 UTC, simonguo commented on src/Nav/test/NavMenuSpec.tsx
> +      assert.isNull(getByText('Submenu').querySelector('.rs-dropdown-menu-toggle-icon'));
rsuite 里面用 chai 作为测试断言，推荐采用 BDD 风格： https://www.chaijs.com/api/bdd/

2022-12-07 11:47 UTC, Yuiai01 commented on src/Nav/test/NavMenuSpec.tsx
> +      assert.isNull(getByText('Submenu').querySelector('.rs-dropdown-menu-toggle-icon'));
> rsuite 里面用 chai 作为测试断言，推荐采用 BDD 风格： https://www.chaijs.com/api/bdd/

嗯嗯，感谢大佬

2022-12-08 03:54 UTC, SevenOutman commented
@Yuiai01 Thanks!

2022-12-08 03:54 UTC, merged

2022-12-08 04:46 UTC, Yuiai01 commented
> @Yuiai01 Thanks!

 Glad to help.