test: replace `done` callback with async assertions
rsuite/rsuite pull request #2999
Opened 2023-01-03 08:30 UTC by SevenOutman

2023-01-05 05:54 UTC, simonguo requested changes

2023-01-05 05:54 UTC, simonguo commented on src/Breadcrumb/test/BreadcrumbSpec.tsx
> +import Sinon from 'sinon';
`sinon` is imported 2 times.

2023-01-06 05:44 UTC, SevenOutman commented on src/Breadcrumb/test/BreadcrumbSpec.tsx
> +import Sinon from 'sinon';
Duplicated imports are removed.

2023-01-10 02:28 UTC, simonguo approved these changes

2023-01-11 02:42 UTC, merged