fix(Nav.Menu): open with hover trigger in Navbar
rsuite/rsuite pull request #3041
Opened 2023-01-30 09:32 UTC by SevenOutman

Fix #2431

2023-01-30 10:21 UTC, simonguo requested changes

2023-01-30 10:21 UTC, simonguo commented on src/Disclosure/Disclosure.tsx
> +      console.log('mouseenter');
Logs not removed

2023-01-31 02:21 UTC, SevenOutman commented on src/Disclosure/Disclosure.tsx
> +      console.log('mouseenter');
Removed now

2023-01-31 06:39 UTC, simonguo approved these changes

2023-02-01 02:34 UTC, merged