fix(Form.Control): fix `acceptor` prop can not accept `Toggle`
rsuite/rsuite pull request #3048
Opened 2023-01-31 10:49 UTC by simonguo

fix: https://github.com/rsuite/rsuite/issues/3036#issuecomment-1408365439

2023-02-01 02:43 UTC, SevenOutman requested changes

2023-02-01 02:43 UTC, SevenOutman commented on src/FormControl/test/FormControlSpec.tsx
> +import Toggle from '../..//Toggle';
Incorrect import path

2023-02-01 03:30 UTC, simonguo commented on src/FormControl/test/FormControlSpec.tsx
> +import Toggle from '../..//Toggle';
```suggestion
import Toggle from '../../Toggle';
```

2023-02-02 03:18 UTC, SevenOutman approved these changes

2023-02-02 03:18 UTC, merged

2023-03-15 02:02 UTC, ab-pm commented
This breaks code that passes a custom value to the `<Toggle>` via the `checked` property:
```js
<Form.Control
  name="…"
  accepter={Toggle}
  checked={myValue}
/>
```
Previously, the form control would forward the `checked` value to the `Toggle`. Now, it does overwrite the `...rest` with the `...accepterProps` containing a `checked` value from the form context. One can workaround this by passing it as `value`, like
```js
<Form.Control
  name="…"
  accepter={Toggle}
  value={myValue}
/>
```
but that's weird to pass a `value` prop to affect the `checked` prop.

I would suggest you either
* change the order of spreads to `{...accepterProps} {...rest}` or
* you already take the `value` and `defaultValue` not directly from `props` but rather use the custom keys, i.e. `props[valueKey]` and `props[defaultValueKey]`.

2023-03-15 06:44 UTC, SevenOutman commented
> This breaks code that passes a custom value to the `<Toggle>` via the `checked` property:
> 
> ```js
> <Form.Control
>   name="…"
>   accepter={Toggle}
>   checked={myValue}
> />
> ```

Hi @ab-pm, as Form.Control now controls the `checked` value of Toggle, you may want to pass `myValue` to Toggle via `formValue` (which expectedly didn't work before).

2023-03-15 09:59 UTC, ab-pm commented
Yes, it's nice that this works now. But sometimes there are cases where you want to override the value taken from the `formValue` per Form.Control, which usually works by passing it directly to `<Form.Control value={myInputText} />`. This approach is no longer working for `Toggle` accepters, which is *not intuitive*.
(An alternative solution for #3036 would have been to align `<Toggle>` with the other input components by making it take a `value` instead of a `checked` prop, but I understand this would have been a larger breaking change)
Sure I can change all my code to use `value` instead of `checked`, or in some places I might be able to adjust the `formValue` objects, but I'd prefer not having to do either of those things.

2023-03-16 06:19 UTC, SevenOutman commented
> But sometimes there are cases where you want to override the value taken from the `formValue` per Form.Control, which usually works by passing it directly to `<Form.Control value={myInputText} />`

This use case makes sense to me. I'm going to fix it.