test(Tag/TagGroup): drop use of getDOMNode util
rsuite/rsuite pull request #3222
Opened 2023-05-30 05:45 UTC by leon-fong

drop use of getDOMNode util

This update involves changes to two components: Tag and TagGroup.

2023-05-31 02:27 UTC, SevenOutman commented
Hi @leon-fong, thanks for contributing this edit! However it looks like some test cases are failing, please fix them first.

2023-05-31 03:28 UTC, leon-fong commented
> thanks for contributing this edit! However it looks like some test cases are failing, please fix them first.

@SevenOutman I have fixed the test cases and re-submitted the edit. Please let me know if there are any further issues.

2023-06-01 02:10 UTC, SevenOutman commented
> I have fixed the test cases and re-submitted the edit. Please let me know if there are any further issues.

The test is still failing.

You could find in the [logs](https://github.com/rsuite/rsuite/actions/runs/5128451997/jobs/9232292462?pr=3222) that the `instanceRef.current` was `null`. It's probably caused by using the wrong `render`.

<img width="458" alt="image" src="https://github.com/rsuite/rsuite/assets/8225666/118def6a-9742-4368-8196-726e5ccaea85">

Please run `M={Tag,TagGroup} npm run tdd` to run the test cases on your local machine while you edit the code, and make sure the tests are passing with your changes before pushing.

2023-06-02 02:20 UTC, SevenOutman requested changes
Glad to see the tests passing! I've went over the edit and found some minor changes I would like you to make.

2023-06-02 02:20 UTC, SevenOutman commented on src/Tag/test/TagSpec.tsx
> +    expect(container.firstChild).to.have.class('rs-tag');
Please don't change the purpose of the old test. The updated test should still be checking `rs-tag rs-tag-md rs-tag-default` classes.

2023-06-05 02:23 UTC, SevenOutman approved these changes
LGTM now, thanks @leon-fong!

2023-06-05 02:35 UTC, merged