fix(Stack): supports Fragment children component
rsuite/rsuite pull request #3607
Opened 2024-02-02 08:44 UTC by myNameIsDu

close #3606

2024-02-02 10:27 UTC, simonguo requested changes

2024-02-02 10:36 UTC, myNameIsDu commented on package.json
> +    "@faker-js/faker": "^8.4.0",
<img width="489" alt="image" src="https://github.com/rsuite/rsuite/assets/53305259/18e0bac6-d2c6-4fab-8344-8f7f5f416f3c">
这里有y依赖，但是没有安装这个包，导致在 commit 的时候 tsc 会报错

2024-02-02 10:36 UTC, myNameIsDu commented on src/DateRangePicker/DateRangePicker.tsx
> +            <div>
增加这个功能之后 `Fragment` 会被展开，导致样式错位

2024-02-02 10:53 UTC, myNameIsDu commented on src/Stack/Stack.tsx
> +      {React.Children.map(flattedChildren as React.ReactElement[], (child, index) => {
done

2024-02-02 11:23 UTC, simonguo requested changes

2024-02-02 11:23 UTC, simonguo commented on src/Stack/Stack.tsx
> +      {ReactChildren.map(flattedChildren as React.ReactElement[], (child, index) => {
在 `ReactChildren.map` 中已经处理了是 Fragment 的情况，这里就不需要调用 flattedChildren 了

2024-02-02 11:28 UTC, simonguo commented on src/DateRangePicker/DateRangePicker.tsx
> +            <div>
可以直接使用 `<Stack.Item>`，避免生成一个没有意义 `div` 元素

2024-02-04 02:40 UTC, myNameIsDu commented on src/DateRangePicker/DateRangePicker.tsx
> +            <div>
done

2024-02-04 02:45 UTC, myNameIsDu commented on src/Stack/Stack.tsx
> +      {ReactChildren.map(flattedChildren as React.ReactElement[], (child, index) => {
<img width="719" alt="image" src="https://github.com/rsuite/rsuite/assets/53305259/09243adf-06de-4b83-a60a-a0a7a43c5d8e">

没懂，这个方法里没有处理 `Fragment` 的情况了

2024-02-04 03:07 UTC, simonguo commented on src/Stack/Stack.tsx
> +      {ReactChildren.map(flattedChildren as React.ReactElement[], (child, index) => {
估计不是最新的代码，你合并一下最新的 main 分支的代码

2024-02-06 03:54 UTC, simonguo approved these changes

2024-02-06 03:54 UTC, merged