Fix Nested objects and Arrays for Form Validation
rsuite/rsuite pull request #3628
Opened 2024-02-17 10:29 UTC by giacomoaugello1

- I fixed some errors that were coming up when running the "npm run lint" command, just to be able to commit.
- I made changes to the FormControl and Form components regarding how the "checkResult" object returned by the SchemaModel was parsed. It basically didn't take into account that there could be more than one level of nesting, and also didn't consider arrays.

2024-02-19 03:25 UTC, simonguo requested changes
You should add tests for the changes to Form and FormControl.
https://github.com/rsuite/rsuite/blob/main/CONTRIBUTING.md#testing

2024-02-19 03:25 UTC, simonguo commented on package.json
> +    "typescript": "^4.4.3"
typescript should not be a dependencies, but a devDependencies.

2024-02-19 03:25 UTC, simonguo commented on src/Accordion/Accordion.tsx
> +import type { PanelGroupProps } from '../PanelGroup';
Unrelated code changes to the topic

2024-02-19 03:25 UTC, simonguo commented on src/AutoComplete/Combobox.tsx
> +import type { InputProps } from '../Input';
Unrelated code changes to the topic

2024-02-19 03:25 UTC, simonguo commented on src/DateInput/utils.ts
> +import type { Locale } from 'date-fns';
Unrelated code changes to the topic

2024-02-19 03:25 UTC, simonguo commented on src/DateRangeInput/utils.ts
> +import type { Locale } from 'date-fns';
Unrelated code changes to the topic

2024-02-19 03:25 UTC, simonguo commented on src/FormControl/FormControl.tsx
> +        ? fieldName.replace(/\./g, '.object.').replace(/\[([^\]]*)\]/g, '.array[$1]') +
Polynomial regular expression used on uncontrolled data. [Show more details](https://github.com/rsuite/rsuite/security/code-scanning/6).
may run slow on strings starting with '[' and with many repetitions of '[\'.

2024-02-19 03:25 UTC, simonguo commented on src/internals/Picker/hooks/useCombobox.ts
> +import type { ComboboxContextProps } from '../PickerToggleTrigger';
Unrelated code changes to the topic

2024-02-19 20:18 UTC, giacomoaugello1 commented
Hi Simon,

I will make these changes, but just one more question...

How should I handle the "Unrelated code changes to the topic" warnings?
I edited that code only because the "npm run lint" command was throwing errors, preventing me from pushing the code. However, I can restore those files and force the push if you wish.

I'll let you know as soon as I make the changes.

Best regards,
Giacomo Augello.


> On 19 Feb 2024, at 04:26, Simon Guo ***@***.***> wrote:
> 
> 
> @simonguo requested changes on this pull request.
> 
> You should add tests for the changes to Form and FormControl.
> https://github.com/rsuite/rsuite/blob/main/CONTRIBUTING.md#testing
> 
> In package.json <https://github.com/rsuite/rsuite/pull/3628#discussion_r1493960546>:
> 
> > @@ -68,7 +68,8 @@
>      "react-use-set": "^1.0.0",
>      "react-window": "^1.8.8",
>      "rsuite-table": "^5.18.2",
> -    "schema-typed": "^2.1.3"
> +    "schema-typed": "^2.1.3",
> +    "typescript": "^4.4.3"
> typescript should not be a dependencies, but a devDependencies.
> 
> In src/Accordion/Accordion.tsx <https://github.com/rsuite/rsuite/pull/3628#discussion_r1493961552>:
> 
> > @@ -1,5 +1,6 @@
>  import React from 'react';
> -import PanelGroup, { type PanelGroupProps } from '../PanelGroup';
> +import PanelGroup from '../PanelGroup';
> +import type { PanelGroupProps } from '../PanelGroup';
> Unrelated code changes to the topic
> 
> In src/AutoComplete/Combobox.tsx <https://github.com/rsuite/rsuite/pull/3628#discussion_r1493961586>:
> 
> > @@ -1,6 +1,7 @@
>  import React from 'react';
>  import { useCombobox } from '../internals/Picker';
> -import Input, { type InputProps } from '../Input';
> +import Input from '../Input';
> +import type { InputProps } from '../Input';
> Unrelated code changes to the topic
> 
> In src/DateInput/utils.ts <https://github.com/rsuite/rsuite/pull/3628#discussion_r1493961616>:
> 
> > @@ -1,4 +1,4 @@
> -import { type Locale } from 'date-fns';
> +import type { Locale } from 'date-fns';
> Unrelated code changes to the topic
> 
> In src/DateRangeInput/utils.ts <https://github.com/rsuite/rsuite/pull/3628#discussion_r1493961643>:
> 
> > @@ -1,4 +1,4 @@
> -import { type Locale } from 'date-fns';
> +import type { Locale } from 'date-fns';
> Unrelated code changes to the topic
> 
> In src/internals/Picker/hooks/useCombobox.ts <https://github.com/rsuite/rsuite/pull/3628#discussion_r1493964260>:
> 
> > @@ -1,5 +1,6 @@
>  import { useContext } from 'react';
> -import { ComboboxContextContext, type ComboboxContextProps } from '../PickerToggleTrigger';
> +import { ComboboxContextContext } from '../PickerToggleTrigger';
> +import type { ComboboxContextProps } from '../PickerToggleTrigger';
> Unrelated code changes to the topic
> 
> In src/FormControl/FormControl.tsx <https://github.com/rsuite/rsuite/pull/3628#discussion_r1493964080>:
> 
> > @@ -162,8 +162,9 @@
>  
>    const getFieldError = (fieldName: string) => {
>      if (nestedField) {
> -      const name = fieldName.includes('.')
> -        ? fieldName.replace('.', '.object.') + '.errorMessage'
> +      const name = /[\.\[\]]+/g.test(fieldName)
> +        ? fieldName.replace(/\./g, '.object.').replace(/\[([^\]]*)\]/g, '.array[$1]') +
> Polynomial regular expression used on uncontrolled data. Show more details <https://github.com/rsuite/rsuite/security/code-scanning/6>.
> may run slow on strings starting with '[' and with many repetitions of '['.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/rsuite/rsuite/pull/3628#pullrequestreview-1887482410>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/APS5OMPB77ZJBYF63CYAN5TYULA4RAVCNFSM6AAAAABDNGX2WGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQOBXGQ4DENBRGA>.
> You are receiving this because you authored the thread.
>

2024-02-21 01:48 UTC, simonguo commented
Hi @giacomoaugello1 

> How should I handle the "Unrelated code changes to the topic" warnings?

 You should revert these changes, don't change it.

> I edited that code only because the "npm run lint" command was throwing errors, preventing me from pushing the code. However, I can restore those files and force the push if you wish.

All submitted code must pass the "npm run lint" and "npm run test" checks. If the code does not pass the check, it will not be merged into the main branch. The reason your submitted code has not been checked is that you have downgraded the version of typescript from 4.6.4 to 4.4.3, which caused type export check errors.

I have reviewed your code. Please fix all the problematic code and add test code to resubmit.

2024-03-17 16:36 UTC, closed without merging

2024-03-17 17:31 UTC, giacomoaugello1 commented
Hi Simon,

It's been a while, but I've been quite busy lately. I've added the tests to the schema-typed repository.

Once they're merged, I'll proceed to do the same with the rsuite repository.

Best regards,

Giacomo Augello


> On 19 Feb 2024, at 04:26, Simon Guo ***@***.***> wrote:
> 
> 
> @simonguo requested changes on this pull request.
> 
> You should add tests for the changes to Form and FormControl.
> https://github.com/rsuite/rsuite/blob/main/CONTRIBUTING.md#testing
> 
> In package.json <https://github.com/rsuite/rsuite/pull/3628#discussion_r1493960546>:
> 
> > @@ -68,7 +68,8 @@
>      "react-use-set": "^1.0.0",
>      "react-window": "^1.8.8",
>      "rsuite-table": "^5.18.2",
> -    "schema-typed": "^2.1.3"
> +    "schema-typed": "^2.1.3",
> +    "typescript": "^4.4.3"
> typescript should not be a dependencies, but a devDependencies.
> 
> In src/Accordion/Accordion.tsx <https://github.com/rsuite/rsuite/pull/3628#discussion_r1493961552>:
> 
> > @@ -1,5 +1,6 @@
>  import React from 'react';
> -import PanelGroup, { type PanelGroupProps } from '../PanelGroup';
> +import PanelGroup from '../PanelGroup';
> +import type { PanelGroupProps } from '../PanelGroup';
> Unrelated code changes to the topic
> 
> In src/AutoComplete/Combobox.tsx <https://github.com/rsuite/rsuite/pull/3628#discussion_r1493961586>:
> 
> > @@ -1,6 +1,7 @@
>  import React from 'react';
>  import { useCombobox } from '../internals/Picker';
> -import Input, { type InputProps } from '../Input';
> +import Input from '../Input';
> +import type { InputProps } from '../Input';
> Unrelated code changes to the topic
> 
> In src/DateInput/utils.ts <https://github.com/rsuite/rsuite/pull/3628#discussion_r1493961616>:
> 
> > @@ -1,4 +1,4 @@
> -import { type Locale } from 'date-fns';
> +import type { Locale } from 'date-fns';
> Unrelated code changes to the topic
> 
> In src/DateRangeInput/utils.ts <https://github.com/rsuite/rsuite/pull/3628#discussion_r1493961643>:
> 
> > @@ -1,4 +1,4 @@
> -import { type Locale } from 'date-fns';
> +import type { Locale } from 'date-fns';
> Unrelated code changes to the topic
> 
> In src/internals/Picker/hooks/useCombobox.ts <https://github.com/rsuite/rsuite/pull/3628#discussion_r1493964260>:
> 
> > @@ -1,5 +1,6 @@
>  import { useContext } from 'react';
> -import { ComboboxContextContext, type ComboboxContextProps } from '../PickerToggleTrigger';
> +import { ComboboxContextContext } from '../PickerToggleTrigger';
> +import type { ComboboxContextProps } from '../PickerToggleTrigger';
> Unrelated code changes to the topic
> 
> In src/FormControl/FormControl.tsx <https://github.com/rsuite/rsuite/pull/3628#discussion_r1493964080>:
> 
> > @@ -162,8 +162,9 @@
>  
>    const getFieldError = (fieldName: string) => {
>      if (nestedField) {
> -      const name = fieldName.includes('.')
> -        ? fieldName.replace('.', '.object.') + '.errorMessage'
> +      const name = /[\.\[\]]+/g.test(fieldName)
> +        ? fieldName.replace(/\./g, '.object.').replace(/\[([^\]]*)\]/g, '.array[$1]') +
> Polynomial regular expression used on uncontrolled data. Show more details <https://github.com/rsuite/rsuite/security/code-scanning/6>.
> may run slow on strings starting with '[' and with many repetitions of '['.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/rsuite/rsuite/pull/3628#pullrequestreview-1887482410>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/APS5OMPB77ZJBYF63CYAN5TYULA4RAVCNFSM6AAAAABDNGX2WGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQOBXGQ4DENBRGA>.
> You are receiving this because you authored the thread.
>