Navigation bar Chinese translation
rsuite/rsuite pull request #3665
Opened 2024-03-13 07:10 UTC by dearDreamWeb

Navigation bar Chinese translation

![image](https://github.com/rsuite/rsuite/assets/52070630/3166212d-9b56-48b0-9cde-cbbc0290169a)

2024-03-13 11:26 UTC, simonguo requested changes

2024-03-13 11:26 UTC, simonguo commented on docs/utils/component.config.json
> +    "title": "不稳定 🧪",
`title` sets the title of `hook`, not the translation of `tag`. 

![image](https://github.com/rsuite/rsuite/assets/1203827/39aca9e0-4e81-42f6-8fa6-c282cb4552da)


> https://rsuite-nextjs-git-fork-deardreamweb-main-rsuite.vercel.app/zh/components/use-media-query/

2024-03-14 07:29 UTC, dearDreamWeb commented
I have modified it and changed the translation of hooks. I will not do tag translation for the time being.

2024-03-14 07:32 UTC, simonguo approved these changes

2024-03-14 07:40 UTC, dearDreamWeb commented
I'll resubmit the translation code, it's a bit confusing now.

2024-03-14 07:40 UTC, closed without merging