Feat:loader-play-state prop added
rsuite/rsuite pull request #3875
Opened 2024-07-07 10:56 UTC by jpranays

### Description
This PR introduces a new `loaderPlayState` prop for the Loader spinner component. The `loaderPlayState` prop accepts two values: `"running"` and `"paused"`, allowing users to control the play state of the loader animation.

### Use Cases
1. **Pause and Resume:** In applications with complex loading sequences, it might be necessary to pause the loader animation while certain conditions are being met and resume it afterward.
2. **Accessibility:** Users might want to pause animations to reduce distractions or for accessibility reasons.
3. **User Experience:** Provide better user experience by controlling the visibility and behavior of the loader based on user interactions.

### Implementation Details
- Added a new `loaderPlayState` prop to the Loader component, which defaults to `"running"`.
- Updated the CSS/JS to handle the `"running"` and `"paused"` states appropriately.
- Ensured backward compatibility by setting the default value to `"running"` so existing implementations are not affected.

### Code Example
```jsx
// Usage Example
<Loader loaderPlayState="paused" />

2024-07-08 01:58 UTC, simonguo commented
Hi @jpranays 

I suggest adding a `paused` value to the `speed` prop to indicate the paused state of the loader.

```tsx
// speed:  'fast' | 'normal' | 'slow' | 'paused'
<Loader speed="paused" />
```

2024-07-08 03:37 UTC, jpranays commented
Great idea! I’ll add paused to the speed prop.

2024-07-08 04:09 UTC, simonguo commented
> Great idea! I’ll add paused to the speed prop.

 Also, remember to add a test case for this to ensure it works as expected.
https://github.com/rsuite/rsuite/blob/main/src/Loader/test/LoaderSpec.tsx#L36

2024-07-08 10:15 UTC, jpranays commented
> > Great idea! I’ll add paused to the speed prop.
> 
> Also, remember to add a test case for this to ensure it works as expected. https://github.com/rsuite/rsuite/blob/main/src/Loader/test/LoaderSpec.tsx#L36

PR updated

2024-07-10 04:24 UTC, simonguo requested changes
https://github.com/rsuite/rsuite/assets/1203827/fba2e79d-0fb2-435f-b85e-7be9bf768b11

The `paused` value doesn't work, check your CSS specificity. You can add an example to the docs to preview it.

https://github.com/rsuite/rsuite/blob/main/docs/pages/components/loader/fragments/speed.md

And the documentation needs to be modified.
https://github.com/rsuite/rsuite/blob/main/docs/pages/components/loader/en-US/index.md#loader-1
https://github.com/rsuite/rsuite/blob/main/docs/pages/components/loader/zh-CN/index.md#loader

2024-07-10 06:00 UTC, jpranays commented
> Jietu20240710-121558-HD.mp4 
> The `paused` value doesn't work, check your CSS specificity. You can add an example to the docs to preview it.
> 
> https://github.com/rsuite/rsuite/blob/main/docs/pages/components/loader/fragments/speed.md
> 
> And the documentation needs to be modified. https://github.com/rsuite/rsuite/blob/main/docs/pages/components/loader/en-US/index.md#loader-1 https://github.com/rsuite/rsuite/blob/main/docs/pages/components/loader/zh-CN/index.md#loader

Seems strange, works fine for me,

https://github.com/rsuite/rsuite/assets/63608934/6628dff9-6d50-4ce0-821f-3de8293f67b6


https://github.com/rsuite/rsuite/assets/63608934/47aa5ae8-935d-4681-90da-7298f3073c5f


Docs have been updated

2024-07-10 06:06 UTC, jpranays commented
> Not working https://rsuite-nextjs-git-fork-jpranays-main-rsuite.vercel.app/components/loader/#speed


https://github.com/rsuite/rsuite/assets/63608934/e32d2938-ee1d-4da9-9315-85e97ca3b4bc

2024-07-10 06:07 UTC, simonguo commented
It works now. It didn't work before because of browser cache.

2024-07-10 06:09 UTC, simonguo approved these changes

2024-07-12 09:23 UTC, merged