Test/removing get dom node
rsuite/rsuite pull request #3943
Opened 2024-08-24 20:32 UTC by Chriscaracach

Why I am doing this: https://github.com/rsuite/rsuite/discussions/3200
What I did: removed use of getDOMNode

This PR involves the following components: RadioGroup, RangeSlider, SelectPicker

2024-08-28 14:18 UTC, simonguo requested changes

2024-08-28 14:18 UTC, simonguo commented on src/SelectPicker/test/SelectPickerSpec.tsx
> -    });
This test case should not be removed

2024-09-09 20:27 UTC, Chriscaracach commented on src/SelectPicker/test/SelectPickerSpec.tsx
> -    });
Sorry, unintended. I will fix it.

2024-09-10 03:14 UTC, simonguo requested changes
There are a lot of changes that shouldn't be part of this PR.

2024-09-10 03:14 UTC, simonguo commented on CHANGELOG.md
> +
Changes that should not be part of this PR

2024-09-20 06:49 UTC, merged